### ISSUE TITLE
File not found 

### ISSUE THREAD

**Issue by bzhtitude** [technologiescollege/Blockly-at-rduino_offline#1]
En lançant l'executable "BlocklyArduino_off.exe" Light s'ouvre mais on tombe sur le message suivant : 

File not found
Firefox can’t find the file at /F:/Logiciels/Arduino_graphique/Blockly-at rduino_offline/wwwBlockly@rduino/index.html.

Ce n'est pas le bon lien absolu mais soucis mineur car on peut quand même "jouer" avec blockly en ouvrant index.html dans Light.

Merci pour cette version de Blockly qui correspond pleinement à mes besoins.

Bzh

**Comment by SebCanet** [comment]
Bonjour,
j'ai tout remanié, merci de faire la mise à jour. Maintenant le lanceur dispose d'un fichier INI à compléter avec la bonne URL en fonction de ce que l'on veut configurer pour les débutants. Il suffit de tester en ligne, cocher à chaque fois "ajouter dans l'URL" puis copier-coller cette URL dans le fichier INI à la section [URL]
