### ISSUE TITLE
impossible de lancer l'exe

### ISSUE THREAD

**Issue by bzhtitude** [technologiescollege/Blockly-at-rduino_offline#2]
j'ai télécharger la version de offline et ça marche plus du tout... je ne vois pas du tout ce que ça peut être, je roule sur la version précédente pour le moment.

![capture1](https://user-images.githubusercontent.com/29465994/31250191-58520f5c-aa1a-11e7-8f71-631b7340b62e.PNG)

**Comment by SebCanet** [comment]
solved
